import fs from 'fs';
import path from 'path';

/**
 * OpenClaw Studio Core Engine Prototype
 * Converts Node JSON to SKILL.md format
 */

export class SkillCompiler {
  constructor(templatesDir) {
    this.templatesDir = templatesDir;
  }

  compile(graph) {
    let markdown = `# Generated Skill\n\n`;
    
    // Simple linear flow for prototype
    const nodes = graph.nodes;
    
    markdown += `## Flow\n\n`;
    
    nodes.forEach((node, index) => {
      markdown += `${index + 1}. **${node.name}** (${node.type})\n`;
      if (node.params && Object.keys(node.params).length > 0) {
        markdown += `   - Params: ${JSON.stringify(node.params)}\n`;
      }
    });

    markdown += `\n## OpenClaw SKILL.md Implementation\n\n`;
    markdown += `> This skill was automatically generated by OpenClaw Studio.\n\n`;
    
    // Standard SKILL.md sections
    markdown += `### Description\nAutomated skill from graph.\n\n`;
    markdown += `### Triggers\n`;
    const triggers = nodes.filter(n => n.type === 'trigger');
    triggers.forEach(t => markdown += `- ${t.name}\n`);
    
    markdown += `\n### Actions\n`;
    const actions = nodes.filter(n => n.type === 'action');
    actions.forEach(a => markdown += `- ${a.name}\n`);

    return markdown;
  }
}

// CLI usage for prototype verification
if (import.meta.url === `file://${process.argv[1]}`) {
  const inputPath = process.argv[2];
  if (!inputPath) {
    console.error('Usage: node engine.js <input-graph.json>');
    process.exit(1);
  }

  const graph = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
  const compiler = new SkillCompiler();
  const result = compiler.compile(graph);
  
  console.log(result);
}
