import sys
import json
import datetime
import os

def analyze_failure(task_id, task_name, error_msg, logs=""):
    """
    模擬 ask_ai 子代理的分析邏輯。
    在實際環境中，這可以透過調用 OpenAI API 或 OpenClaw 內部的 LLM 介面。
    """
    
    # 這裡實作初步的啟發式分析
    possible_causes = []
    if "timeout" in error_msg.lower():
        possible_causes.append("網路延遲或 API 響應過慢導致超時。")
    if "401" in error_msg or "unauthorized" in error_msg.lower():
        possible_causes.append("認證失敗，請檢查 API Key 或 Session 是否過期。")
    if "404" in error_msg:
        possible_causes.append("資源未找到，可能是 URL 錯誤或資源已被刪除。")
    if not possible_causes:
        possible_causes.append("系統執行過程中發生未預期的邏輯錯誤，需要進一步排查日誌。")

    solutions = [f"修復建議 1: 基於 '{possible_causes[0]}' 進行優化。"]
    if "timeout" in error_msg.lower():
        solutions.append("修復建議 2: 增加超時重試機制 (Retry Policy)。")
    
    # 生成 Markdown 報告
    log_text = logs if logs else "無提供詳細日誌內容。"
    solutions_text = "".join("- " + s + "\n" for s in solutions)
    now_str = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    report_content = (
        "# 任務複盤報告 (Task Failure Post-Mortem)\n\n"
        "## 1. 基本資訊\n"
        f"- **任務 ID**: {task_id}\n"
        f"- **任務名稱**: {task_name}\n"
        f"- **失敗時間**: {now_str}\n"
        "- **狀態**: Failed 🔴\n\n"
        "## 2. 失敗原因初步分析\n"
        f"- **錯誤訊息**: `{error_msg}`\n"
        "- **分析結論**: \n"
        f"  - {possible_causes[0]}\n"
        "  - 此分析由 OpenClaw `ask_ai` 子代理自動生成。\n\n"
        "## 3. 詳細日誌摘要\n"
        f"{log_text}\n\n"
        "## 4. 可能的解決方案\n"
        f"{solutions_text}\n"
        "## 5. 建議的下一步行動\n"
        "1. 檢查任務參數設定。\n"
        "2. 開發者手動驗證環境變數。\n"
        "3. 若問題持續，請提交 Issue 至系統維護團隊。\n\n"
        "---\n"
        "*Generated by OpenClaw Failure Analysis Sub-agent*\n"
    )
    return report_content

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python3 ai_failure_analyzer.py <id> <name> <error>")
        sys.exit(1)
    
    t_id = sys.argv[1]
    t_name = sys.argv[2]
    t_err = sys.argv[3]
    t_logs = sys.argv[4] if len(sys.argv) > 4 else ""
    
    print(analyze_failure(t_id, t_name, t_err, t_logs))
