#!/bin/bash
# Script to apply the Studio API changes to the main source code
# Generated by Task Executor

SRC_FILES="/Users/sky770825/.openclaw/workspace/sandbox/output/server/src"
DEST_FILES="/Users/sky770825/openclaw任務面版設計/server/src"

echo "Preparing to apply changes to $DEST_FILES..."
if [ ! -d "$DEST_FILES/routes" ]; then
    mkdir -p "$DEST_FILES/routes"
fi

cp "$SRC_FILES/routes/studio.ts" "$DEST_FILES/routes/studio.ts"
cp "$SRC_FILES/index.ts" "$DEST_FILES/index.ts"

echo "Implementation landed successfully in the project source."
