#!/bin/bash
# Local service health checker generated by Task Executor

CHECK_PORTS=(3000 3001 5000 8000 8080)

echo "--- Local Service Health Check ---"
for port in "${CHECK_PORTS[@]}"; do
    echo -n "Checking port $port: "
    if lsof -i :$port > /dev/null; then
        echo "UP (Listening)"
        echo "Response from http://localhost:$port:"
        curl -I -s "http://localhost:$port" | head -n 1 || echo "No HTTP response"
    else
        echo "DOWN"
    fi
done

echo ""
echo "--- Cloudflared Status ---"
if pgrep -x "cloudflared" > /dev/null; then
    echo "cloudflared is running."
else
    echo "cloudflared is NOT running."
fi
