#!/bin/bash
# Tool generated by Claude Code for Task Dashboard Analysis
PROJECT_SRC="/Users/caijunchang/openclaw任務面版設計"

echo "=== Task Dashboard Inspector ==="
if [ ! -d "$PROJECT_SRC" ]; then
    echo "Error: Source project not found at $PROJECT_SRC"
    exit 1
fi

echo "Searching for UI Components..."
find "$PROJECT_SRC/src" -name "*Card*" -o -name "*Board*" -o -name "*Task*" 2>/dev/null

echo "Searching for API endpoints in server..."
grep -r "router\." "$PROJECT_SRC/server/src" 2>/dev/null || echo "No API routes found or access denied."

echo "Analysis complete."
