import fs from 'fs';

export class SkillCompiler {
  compile(graph) {
    const nodes = graph.nodes || [];
    let markdown = '# Generated Skill\n\n';
    
    markdown += '## Logic & Conditions\n';
    const conditions = nodes.filter(n => n.type === 'condition');
    if (conditions.length > 0) {
      conditions.forEach(c => {
        markdown += - IF ${c.name}: ${c.params?.logic || 'default logic'}\n;
      });
    } else {
      markdown += '- (No complex logic defined)\n';
    }

    markdown += '\n## Execution Steps\n';
    const actions = nodes.filter(n => n.type === 'action');
    actions.forEach((a, i) => {
      markdown += ${i + 1}. ${a.name}: ${a.params?.desc || 'Execute'}\n;
    });

    markdown += '\n> Generated by OpenClaw Studio Core v1.1\n';
    return markdown;
  }
}
